Repository nanoframework/nanoFirmwareFlasher, pull requests merged in 2021-03, with the labels that each got.

#44 Fix ST devices that cannot handle DFU packages
  nanoFirmwareFlasher/Program.cs
  nanoFirmwareFlasher/Stm32Firmware.cs
  nanoFirmwareFlasher/Stm32Operations.cs
Labels: Type: enhancement

#46 Fix exception when downloading file for a new target
  nanoFirmwareFlasher/FirmwarePackage.cs
Labels: Type: bug

#48 Replace Bintray repo with Cloudsmith
  nanoFirmwareFlasher/CC13x26x2Firmware.cs
  nanoFirmwareFlasher/CloudsmithPackageInfo.cs
  nanoFirmwareFlasher/Esp32Firmware.cs
  nanoFirmwareFlasher/ExitCodes.cs
  nanoFirmwareFlasher/FirmwarePackage.cs
  nanoFirmwareFlasher/Options.cs
  nanoFirmwareFlasher/Program.cs
  nanoFirmwareFlasher/Stm32Firmware.cs
  version.json
Labels: Breaking-Change
