Repository nanoframework/nanoFirmwareFlasher, pull requests merged in 2021-05, with the labels that each got.

#50 Help option improvements for ESP32
  nanoFirmwareFlasher/Options.cs
Labels: Type: enhancement

#51 Fix fwversion parameter not pulling the correct file
  nanoFirmwareFlasher/FirmwarePackage.cs
Labels: CI: Publish Release, Type: bug

#53 Correct the way nanoff chooses the partition to erase.
  nanoFirmwareFlasher/Esp32Firmware.cs
  nanoFirmwareFlasher/Esp32Operations.cs
Labels: Type: bug

#52 Add option to specify partition table size
  nanoFirmwareFlasher/Esp32Firmware.cs
  nanoFirmwareFlasher/Esp32Operations.cs
  nanoFirmwareFlasher/EspTool.cs
  nanoFirmwareFlasher/Options.cs
  nanoFirmwareFlasher/Program.cs
  nanoFirmwareFlasher/nanoFirmwareFlasher.csproj
Labels: Type: enhancement
