Repository nanoframework/nanoFirmwareFlasher, pull requests merged in 2021-11, with the labels that each got.

#92 Fix FEATHER_S2 update
  nanoFirmwareFlasher/Esp32Operations.cs
  nanoFirmwareFlasher/EspTool.cs
  nanoFirmwareFlasher/FirmwarePackage.cs
Labels: Type: bug, Type: enhancement

#93 Fix deployment operation for ESP32
  README.md
  nanoFirmwareFlasher/Esp32Firmware.cs
  nanoFirmwareFlasher/Esp32Operations.cs
  nanoFirmwareFlasher/Program.cs
  version.json
Labels: Type: bug, Breaking-Change

#94 Improve message when updating ESP32-S2 without target name
  nanoFirmwareFlasher/Esp32Operations.cs
Labels: Type: enhancement

#95 Improve warning visibility
  nanoFirmwareFlasher/StmDeviceBase.cs
  nanoFirmwareFlasher/nanoFirmwareFlasher.csproj
Labels: Type: enhancement

#96 Improve listing of available targets
  README.md
  nanoFirmwareFlasher/ExitCodes.cs
  nanoFirmwareFlasher/FirmwarePackage.cs
  nanoFirmwareFlasher/Options.cs
  nanoFirmwareFlasher/Program.cs
Labels: Type: enhancement, Type: documentation

#97 Improve package filtering
  nanoFirmwareFlasher/FirmwarePackage.cs
  nanoFirmwareFlasher/Options.cs
  nanoFirmwareFlasher/Program.cs
Labels: Breaking-Change, Type: enhancement
