Repository nanoframework/nanoFirmwareFlasher, pull requests merged in 2022-12, with the labels that each got.

#182 Fix JLink error codes
  nanoFirmwareFlasher.Library/ExitCodes.cs
  nanoFirmwareFlasher.Library/JLinkCli.cs
  nanoFirmwareFlasher.Tool/Program.cs
Labels: Type: enhancement

#183 Improvements in JLink flash
  nanoFirmwareFlasher.Library/JLinkCli.cs
Labels: Type: bug, Type: enhancement

#185 Fix CI naming issue
  azure-pipelines.yml
Labels: Area: Config-and-Build

#189 Fix Readme link
  README.md
Labels: Type: documentation

#190 Improve output of new version notice
  nanoFirmwareFlasher.Tool/Program.cs
Labels: Type: enhancement

#191 Fix error code on missing bin file for J-Link flash
  nanoFirmwareFlasher.Library/JLinkCli.cs
Labels: Type: bug

#192 Improve flashing with J-Link
  nanoFirmwareFlasher.Library/JLinkCli.cs
Labels: Type: enhancement

#193 Remove duplicated version notice
  nanoFirmwareFlasher.Tool/Program.cs
Labels: Type: bug

#194 Improve output of J-Link probe details
  nanoFirmwareFlasher.Library/JLinkDevice.cs
  nanoFirmwareFlasher.Library/JLinkOperations.cs
  nanoFirmwareFlasher.Tool/Program.cs
Labels: Type: enhancement

#195 Output from J-Link CLI is now output on diagnostic
  nanoFirmwareFlasher.Library/JLinkCli.cs
Labels: Type: enhancement

#197 Fix usage of relative paths
  nanoFirmwareFlasher.Library/Esp32Operations.cs
  nanoFirmwareFlasher.Library/JLinkCli.cs
  nanoFirmwareFlasher.Library/StmDeviceBase.cs
  nanoFirmwareFlasher.Library/Utilities.cs
Labels: Type: enhancement

#127 Add unit test skeleton
  nanoFirmwareFlasher.Tests/CloudsmithApiTests.cs
  nanoFirmwareFlasher.Tests/FirmwarePackageTests.cs
  nanoFirmwareFlasher.Tests/nanoFirmwareFlasher.Tests.csproj
  nanoFirmwareFlasher.sln
Labels: Type: Unit Tests
