Repository nanoframework/nanoFirmwareFlasher, pull requests merged in 2022-03, with the labels that each got.

#122 Improve message requesting target name for ESP32-S2 series
  nanoFirmwareFlasher/Esp32Operations.cs
Labels: Type: enhancement

#121 Fix parsing of detection data for ESP32-S2
  nanoFirmwareFlasher/EspTool.cs
Labels: Type: bug

#124 Fix CloudSimth requestUri
  nanoFirmwareFlasher.sln
  nanoFirmwareFlasher/FirmwarePackage.cs
Labels: Type: bug

#126 Fix issue with query to Cloudsmith
  nanoFirmwareFlasher/FirmwarePackage.cs
Labels: Type: bug, CI: Update Dependents
