Repository nanoframework/nanoFirmwareFlasher, pull requests merged in 2022-02, with the labels that each got.

#108 Add listports to list available COM ports
  README.md
  nanoFirmwareFlasher/Options.cs
  nanoFirmwareFlasher/Program.cs
Labels: Type: enhancement

#111 Update bootloader for IDF 4.4
  lib/esp32bootloader/bootloader.bin
  lib/esp32bootloader/test_startup.bin
  lib/esp32s2bootloader/bootloader.bin
  lib/esp32s2bootloader/test_startup.bin
Labels: Type: dependencies

#112 Add script to update esptool
  update-esptool.ps1
Labels: Area: Config-and-Build

#109 Add option to clear fw location cache
  README.md
  nanoFirmwareFlasher/ExitCodes.cs
  nanoFirmwareFlasher/FirmwarePackage.cs
  nanoFirmwareFlasher/Options.cs
  nanoFirmwareFlasher/Program.cs
Labels: Type: enhancement, Type: documentation, CI: Update Dependents

#115 Improve help text
  nanoFirmwareFlasher/Options.cs
  nanoFirmwareFlasher/Program.cs
Labels: Type: documentation

#116 Rework packaging
  azure-pipelines.yml
  nanoFirmwareFlasher/nanoFirmwareFlasher.csproj
Labels: Area: Config-and-Build, CI: Update Dependents

#117 Fix parsing from esptool
  nanoFirmwareFlasher/EspTool.cs
Labels: Type: bug

#118 Improve output regarding ESP32 PSRAM availability
  nanoFirmwareFlasher/Esp32DeviceInfo.cs
  nanoFirmwareFlasher/EspTool.cs
  nanoFirmwareFlasher/PSRamAvailability.cs
Labels: Type: enhancement

#119 Improve output of target list
  nanoFirmwareFlasher/Program.cs
Labels: Type: enhancement

#120 Improve queries to Cloudsmith API
  nanoFirmwareFlasher/FirmwarePackage.cs
Labels: Type: enhancement
