Repository nanoframework/nanoFirmwareFlasher, pull requests merged in 2023-04, with the labels that each got.

#208 Fixing DFU detection for PyBStick and DFU Driver installation
  nanoFirmwareFlasher.Tool/Program.cs
Labels: Type: bug

#210 Add support for updating CLR and deploy app using serial port
  README.md
  nanoFirmwareFlasher.Library/FirmwarePackageFactory.cs
  nanoFirmwareFlasher.Library/NanoDeviceOperations.cs
  nanoFirmwareFlasher.Tool/Options.cs
  nanoFirmwareFlasher.Tool/Program.cs
Labels: Type: enhancement, Type: documentation

#198 Improve CI build speed
  azure-pipelines.yml
Labels: Area: Config-and-Build
