Repository nanoframework/nanoFirmwareFlasher, pull requests merged in 2023-07, with the labels that each got.

#234 Update ESP32 bootloader to IDF 4.4.5
  lib/esp32bootloader/bootloader.bin
  lib/esp32bootloader/test_startup.bin
  lib/esp32s2bootloader/bootloader.bin
  lib/esp32s2bootloader/test_startup.bin
Labels: Type: dependencies

#235 Improve error message on ESP32 bootloader failure
  nanoFirmwareFlasher.Library/EspTool.cs
Labels: Type: enhancement

#236 Fix ESP32 revision parsing
  nanoFirmwareFlasher.Library/Esp32Operations.cs
Labels: Type: bug, Type: enhancement

#237 Fix check of ESP32-S3 version
  nanoFirmwareFlasher.Library/Esp32Operations.cs
Labels: Type: enhancement

#238 Fix revision strings for ESP32-S3
  nanoFirmwareFlasher.Library/Esp32Operations.cs
Labels: Type: bug

#239 Optimize Chinese README translation
  README.zh-cn.md
Labels: Type: documentation
