Repository nanoframework/nanoFirmwareFlasher, pull requests merged in 2023-12, with the labels that each got.

#251 Add telemetry to application
  README.md
  azure-pipelines.yml
  common.ps1
  nanoFirmwareFlasher.Library/FirmwarePackage.cs
  nanoFirmwareFlasher.Library/appsettings.json
  nanoFirmwareFlasher.Library/nanoFirmwareFlasher.Library.csproj
  nanoFirmwareFlasher.Library/packages.lock.json
  nanoFirmwareFlasher.Tool/packages.lock.json
Labels: Area: Config-and-Build, Type: enhancement, Type: documentation

#252 Error description is now output for verbosity normal
  nanoFirmwareFlasher.Tool/Program.cs
Labels: Type: enhancement

#253 Rework telemetry client
  azure-pipelines.yml
  nanoFirmwareFlasher.Library/FirmwarePackage.cs
  nanoFirmwareFlasher.Library/NanoTelemetryClient.cs
  nanoFirmwareFlasher.Library/appsettings.json
  nanoFirmwareFlasher.Library/nanoFirmwareFlasher.Library.csproj
  nanoFirmwareFlasher.Tool/Program.cs
  nanoFirmwareFlasher.Tool/appsettings.json
  nanoFirmwareFlasher.Tool/nanoFirmwareFlasher.Tool.csproj
Labels: Type: bug, Type: enhancement

#254 Improve update operation for ESP32
  nanoFirmwareFlasher.Library/Esp32Operations.cs
  nanoFirmwareFlasher.Library/EspTool.cs
  nanoFirmwareFlasher.Library/FirmwarePackage.cs
  nanoFirmwareFlasher.Tool/Esp32Manager.cs
Labels: Type: bug, Breaking-Change, Type: enhancement
