Repository nanoframework/nanoFirmwareFlasher, pull requests merged in 2023-10, with the labels that each got.

#241 Allow either bin or hex file to be used for STM32 DFU update
  nanoFirmwareFlasher.Tool/Program.cs
Labels: Type: bug, hacktoberfest-accepted

#242 Add manager classes for platform-specific operations
  nanoFirmwareFlasher.Library/Exceptions/NoOperationPerformedException.cs
  nanoFirmwareFlasher.Library/Exceptions/SilinkExecutionException.cs
  nanoFirmwareFlasher.Library/IManager.cs
  nanoFirmwareFlasher.Tool/Esp32Manager.cs
  nanoFirmwareFlasher.Tool/NanoDeviceManager.cs
  nanoFirmwareFlasher.Tool/Program.cs
  nanoFirmwareFlasher.Tool/SilabsManager.cs
  nanoFirmwareFlasher.Tool/Stm32Manager.cs
  nanoFirmwareFlasher.Tool/TIManager.cs
Labels: Type: enhancement, hacktoberfest-accepted

#243 Fix output for progress messages with ESP32 operations
  nanoFirmwareFlasher.Library/Esp32Operations.cs
  nanoFirmwareFlasher.Library/EspTool.cs
Labels: Type: bug

#244 Fix platform check
  nanoFirmwareFlasher.Tool/NanoDeviceManager.cs
  nanoFirmwareFlasher.Tool/Options.cs
  nanoFirmwareFlasher.Tool/SilabsManager.cs
  nanoFirmwareFlasher.Tool/TIManager.cs
Labels: Type: bug

#247 Fix deployment operation with J-Link
  nanoFirmwareFlasher.Library/JLinkCli.cs
  nanoFirmwareFlasher.Tool/SilabsManager.cs
Labels: Type: bug, Type: enhancement

#249 Fix output of device operations
  nanoFirmwareFlasher.Tool/NanoDeviceManager.cs
  nanoFirmwareFlasher.Tool/Program.cs
Labels: Type: bug
