Repository nanoframework/nanoFirmwareFlasher, pull requests merged in 2024-06, with the labels that each got.

#274 Fix S3 broken --masserase option
  nanoFirmwareFlasher.Library/EspTool.cs
Labels: Type: bug

#276 Fix collection initializers
  nanoFirmwareFlasher.Library/CC13x26x2Operations.cs
  nanoFirmwareFlasher.Library/Esp32Operations.cs
  nanoFirmwareFlasher.Library/JLinkCli.cs
  nanoFirmwareFlasher.Library/JLinkOperations.cs
  nanoFirmwareFlasher.Library/Stm32Operations.cs
  nanoFirmwareFlasher.Library/nanoFirmwareFlasher.Library.csproj
  nanoFirmwareFlasher.Tool/Program.cs
  nanoFirmwareFlasher.Tool/nanoFirmwareFlasher.Tool.csproj
Labels: Area: Config-and-Build, CI: Update Dependents

#277 Migrate to .NET 8.0
  nanoFirmwareFlasher.Library/CC13x26x2Firmware.cs
  nanoFirmwareFlasher.Library/CC13x26x2Operations.cs
  nanoFirmwareFlasher.Library/Esp32Firmware.cs
  nanoFirmwareFlasher.Library/Esp32Operations.cs
  nanoFirmwareFlasher.Library/FileDeployment/FileDeploymentManager.cs
  nanoFirmwareFlasher.Library/FirmwarePackage.cs
  nanoFirmwareFlasher.Library/JLinkCli.cs
  nanoFirmwareFlasher.Library/JLinkDevice.cs
  nanoFirmwareFlasher.Library/JLinkOperations.cs
  nanoFirmwareFlasher.Library/NanoDeviceOperations.cs
  nanoFirmwareFlasher.Library/Stm32Operations.cs
  nanoFirmwareFlasher.Library/StmDfuDevice.cs
  nanoFirmwareFlasher.Library/StmJtagDevice.cs
  nanoFirmwareFlasher.Library/nanoFirmwareFlasher.Library.csproj
  nanoFirmwareFlasher.Library/packages.lock.json
  nanoFirmwareFlasher.Tool/Options.cs
  nanoFirmwareFlasher.Tool/Program.cs
  nanoFirmwareFlasher.Tool/SilabsManager.cs
  nanoFirmwareFlasher.Tool/nanoFirmwareFlasher.Tool.csproj
  nanoFirmwareFlasher.Tool/packages.lock.json
Labels: Area: Config-and-Build, Breaking-Change, CI: Update Dependents

#278 Fix relative path file for bin files in JLink
  nanoFirmwareFlasher.Library/JLinkCli.cs
Labels: Type: bug

#280 Improvements in JLink operations
  nanoFirmwareFlasher.Library/JLinkCli.cs
Labels: Type: enhancement, CI: Update Dependents

#282 JLink operations don't delete files anymore
  nanoFirmwareFlasher.Library/JLinkCli.cs
Labels: Type: bug

#281 Improve output during backup/flash process
  nanoFirmwareFlasher.Library/Esp32Operations.cs
  nanoFirmwareFlasher.Library/EspTool.cs
Labels: Type: enhancement
