Repository nanoframework/nanoFirmwareFlasher, pull requests merged in 2024-04, with the labels that each got.

#264 PSRAM discovery is now performed for all targets
  nanoFirmwareFlasher.Library/EspTool.cs
Labels: Breaking-Change, Type: enhancement

#266 Revert "PSRAM discovery is now performed for all targets (#264)"
  nanoFirmwareFlasher.Library/EspTool.cs
Labels: Type: bug

#265 Fix issues with file paths for GGecko updates
  nanoFirmwareFlasher.Library/JLinkCli.cs
Labels: Type: enhancement
