Repository nanoframework/nanoFirmwareFlasher, pull requests merged in 2025-01, with the labels that each got.

#308 Hard reset added for several ESP32 options missing it
  nanoFirmwareFlasher.Library/Esp32Operations.cs
  nanoFirmwareFlasher.Library/EspTool.cs
  nanoFirmwareFlasher.Tool/Esp32Manager.cs
Labels: Type: enhancement

#310 Fix platform names
  README.md
  nanoFirmwareFlasher.Library/SupportedPlatform.cs
  nanoFirmwareFlasher.Tool/Options.cs
  nanoFirmwareFlasher.Tool/Program.cs
  nanoFirmwareFlasher.Tool/SilabsManager.cs
Labels: Breaking-Change, Type: enhancement

#311 Change the way of getting base directory
  nanoFirmwareFlasher.Library/Utilities.cs
Labels: Type: Bug
